"""empty message

Revision ID: df8e6b5e1bc9
Revises: 
Create Date: 2023-05-22 20:02:36.723559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "df8e6b5e1bc9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_item")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("item")
    # ### end Alembic commands ###
